CREATE TABLE IF NOT EXISTS historical_admission_data (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    school_id BIGINT NOT NULL,
    school_name VARCHAR(100) NOT NULL,
    year INT NOT NULL,
    admission_score DECIMAL(5,2),
    lowest_score DECIMAL(5,2),
    highest_score DECIMAL(5,2),
    average_score DECIMAL(5,2),
    enrollment_quota INT,
    applicant_count INT,
    admission_rate DECIMAL(5,2),
    city VARCHAR(50),
    district VARCHAR(50),
    school_type VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_school_id (school_id),
    INDEX idx_year (year),
    INDEX idx_city (city),
    INDEX idx_district (district),
    UNIQUE KEY uk_school_year (school_id, year),
    CONSTRAINT fk_had_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
